[[proxy]]
rewrite = "/api/v1"
backend = "http://satsuma:45289/api/v1"

[[proxy]]
backend = "ws://satsuma:45289/ws"
ws = true

# From:
# https://github.com/autarch/blog.urth.org/blob/next-post/content/posts/2022-02-14-frontend-rust-without-node.md#tailwindcss
[[hooks]]
stage = "build"
command = "sh"
command_arguments = [
    "-c",
    "node_modules/.bin/tailwindcss -i tailwindcss.css -o $TRUNK_STAGING_DIR/index.css"
]

[serve]
address = "0.0.0.0"
port = 8999
