[package]
name = "homectl-server"
version = "0.6.3"
authors = ["Rasmus Lövegren <fruitiex@gmail.com>"]
edition = "2021"
default-run = "homectl-server"

[[bin]]
name = "homectl-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "=1.5.0"
bytes = "=1.5.0"
chrono = { version = "=0.4.31", features = ["serde"] }
config = "=0.13.4"
futures = "=0.3.30"
serde = { version = "=1.0.193", features = ["derive"] }
serde_json = "=1.0.108"
palette = { version = "=0.7.3", features = ["serializing"] }
async-trait = "=0.1.76"
rand = "=0.8.5"
warp = "=0.3.6"
serde_path_to_error = "=0.1.14"
tokio = { version = "=1.35.1", features = ["full"] }
futures-util = "=0.3.30"
tokio-stream = "=0.1.14"
itertools = "=0.12.0"
sqlx = { version = "=0.7.3", features = [
	"runtime-tokio-rustls",
	"postgres",
	"json",
] }
once_cell = "=1.19.0"
rumqttc = "=0.23.0"
toml = "=0.8.8"
json_value_merge = "=2.0.0"
ts-rs = "=7.0.0"
macro-attr = "=0.2.0"
newtype_derive = "=0.1.6"
log = "=0.4.20"
pretty_env_logger = "=0.5.0"
eyre = "=0.6.11"
color-eyre = "=0.6.2"
