[package]
name = "homectl-server"
version = "0.5.1"
authors = ["Rasmus Lövegren <fruitiex@gmail.com>"]
edition = "2021"
default-run = "homectl-server"

[[bin]]
name = "homectl-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
bytes = "1.5.0"
chrono = { version = "0.4.31", features = ["serde"] }
config = "0.13.3"
futures = "0.3.28"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0"
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"
palette = { version = "0.7.3", features = ["serializing"] }
async-trait = "0.1.74"
surf = { version = "2.3.2", default-features = false, features = [
	"h1-client-rustls",
] }
rand = "0.8.5"
wakey = "0.3.0"
warp = "0.3"
serde_path_to_error = "0.1"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.28"
tokio-stream = "0.1.14"
itertools = "0.11.0"
sqlx = { version = "0.7", features = [
	"runtime-tokio-rustls",
	"postgres",
	"json",
] }
once_cell = "1.18.0"
rumqttc = "0.23.0"
toml = "0.8.4"
json_value_merge = "2.0.0"
ts-rs = "7.0.0"
macro-attr = "0.2.0"
newtype_derive = "0.1.6"
log = "0.4.20"
pretty_env_logger = "0.5.0"
eyre = "0.6.8"
color-eyre = "0.6.2"
