// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { GroupId } from "./GroupId";
import type { RolloutStyle } from "./RolloutStyle";
import type { SceneId } from "./SceneId";

/**
 * Contains the information needed to activate a scene as an action.
 */
export type ActivateSceneActionDescriptor = { scene_id: SceneId, 
/**
 * Optionally only apply scene to these devices
 */
device_keys: Array<DeviceKey> | null, 
/**
 * Optionally only apply scene to these groups
 */
group_keys: Array<GroupId> | null, 
/**
 * Optionally opt-in to use scene transition.
 */
use_scene_transition: boolean,
/**
 * Optionally override the transition applied when activating this scene.
 */
transition: number | null, 
/**
 * Optional rollout style for the activation.
 */
rollout: RolloutStyle | null, 
/**
 * Origin device key used by rollout styles that need a source location.
 */
rollout_source_device_key: DeviceKey | null, 
/**
 * Total rollout duration in milliseconds.
 */
rollout_duration_ms: number | null, };
