// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { GroupId } from "./GroupId";
import type { SceneId } from "./SceneId";

/**
 * Contains the information needed to activate a scene
 */
export type ActivateSceneDescriptor = { scene_id: SceneId, 
/**
 * Optionally only apply scene to these devices
 */
device_keys: Array<DeviceKey> | null, 
/**
 * Optionally only apply scene to these groups
 */
group_keys: Array<GroupId> | null, 
/**
 * Optionally opt-in to use scene transition.
 */
use_scene_transition: boolean, 
/**
 * Optionally override the transition applied when activating this scene.
 */
transition: number | null, };
