// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { GroupId } from "./GroupId";
import type { SceneId } from "./SceneId";

/**
 * Contains the information needed to activate a scene
 */
export type ActivateSceneDescriptor = { 
/**
 * Scene to activate. When `mirror_from_group` is set, this acts as a
 * fallback that is used only if the referenced group has no unanimous
 * currently-active scene.
 */
scene_id: SceneId, 
/**
 * If set, resolve the scene to activate from the currently active scene
 * of this group at dispatch time. Falls back to `scene_id` if that group
 * has no unanimous active scene.
 */
mirror_from_group: GroupId | null, 
/**
 * Optionally only apply scene to these devices
 */
device_keys: Array<DeviceKey> | null, 
/**
 * Optionally only apply scene to these groups
 */
group_keys: Array<GroupId> | null, 
/**
 * Whether scene-derived transitions should be preserved during activation.
 */
use_scene_transition: boolean, 
/**
 * Optionally override the transition applied when activating this scene.
 */
transition: number | null, };
