// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { GroupId } from "./GroupId";
import type { RolloutStyle } from "./RolloutStyle";
import type { SceneId } from "./SceneId";

/**
 * Contains the information needed to activate a scene as an action.
 */
export type ActivateSceneActionDescriptor = { 
/**
 * Scene to activate. When `mirror_from_group` is set, this acts as a
 * fallback that is used only if the referenced group has no unanimous
 * currently-active scene.
 */
scene_id: SceneId, 
/**
 * If set, resolve the scene to activate from the currently active scene
 * of this group at dispatch time. Falls back to `scene_id` if that group
 * has no unanimous active scene.
 */
mirror_from_group: GroupId | null, 
/**
 * Optionally only apply scene to these devices
 */
device_keys: Array<DeviceKey> | null, 
/**
 * Optionally only apply scene to these groups
 */
group_keys: Array<GroupId> | null, 
/**
 * If true, extend `group_keys` with every group that contains the
 * triggering device at rule-evaluation time. No-op for actions that are
 * not triggered by a device event (e.g. `ForceTriggerRoutine`).
 */
include_source_groups: boolean, 
/**
 * Whether scene-derived transitions should be preserved during activation.
 */
use_scene_transition: boolean, 
/**
 * Optionally override the transition applied when activating this scene.
 */
transition: number | null, 
/**
 * Optional rollout style for the activation.
 */
rollout: RolloutStyle | null, 
/**
 * Origin device key used by rollout styles that need a source location.
 */
rollout_source_device_key: DeviceKey | null, 
/**
 * Total rollout duration in milliseconds.
 */
rollout_duration_ms: number | null, };
