// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Review selection. Omitted means all proposed changes; an empty list means none.
 */
export type ApplyAssistantActionRequest = { deviceKeys?: Array<string> };
