// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantActionChangeResult } from './AssistantActionChangeResult';

export type ApplyAssistantActionResponse = {
  summary?: string;
  results: Array<AssistantActionChangeResult>;
  appliedCount: number;
};
