// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantOperationResult } from './AssistantOperationResult';

export type ApplyAssistantPlanResponse = {
  results: Array<AssistantOperationResult>;
};
