// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantActionColor } from './AssistantActionColor';

/**
 * One proposed light-state change. Values are clamped during validation and
 * applied through the normal device command path only when the user applies.
 */
export type AssistantActionChange = {
  deviceKey: string;
  name?: string;
  power?: boolean;
  brightness?: number;
  color?: AssistantActionColor;
};
