// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who authored one turn of the conversation history.
 */
export type AssistantMessageRole = 'user' | 'assistant';
