// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Approximate context usage for the current thread. Token counts come from
 * the provider when it reports them and are estimated from character counts
 * otherwise (`approximate` is true in that case).
 */
export type AssistantUsage = {
  promptTokens: bigint;
  completionTokens: bigint;
  totalTokens: bigint;
  contextWindow: bigint;
  approximate: boolean;
};
