// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantAction } from './AssistantAction';
import type { AssistantPlan } from './AssistantPlan';

/**
 * A proposed plan or light-state action stored alongside the thread turn that
 * produced it.
 */
export type AssistantThreadProposal =
  | { kind: 'plan'; plan: AssistantPlan }
  | { kind: 'action'; action: AssistantAction };
