// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantEntityKind } from './AssistantEntityKind';

/**
 * A context entity the user attached to the assistant prompt.
 */
export type AssistantAttachment = {
  kind: AssistantEntityKind;
  id?: string;
  label?: string;
};
