// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantEntityKind } from './AssistantEntityKind';

/**
 * One deterministic search hit for the assistant context builder / UI.
 */
export type AssistantSearchResult = {
  kind: AssistantEntityKind;
  id: string;
  label: string;
  summary: string;
};
