// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantMessageRole } from "./AssistantMessageRole";

/**
 * One earlier conversation turn sent back with a new request. History is
 * client-held and session-only; the server caps and truncates it.
 */
export type AssistantHistoryMessage = { role: AssistantMessageRole, content: string, };
