// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantOperation } from "./AssistantOperation";

export type AssistantPlan = { planId: string, summary: string, operations: Array<AssistantOperation>, createdAtMs: bigint, };
