// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantHistoryMessage } from './AssistantHistoryMessage';

/**
 * A persisted assistant conversation thread.
 */
export type AssistantThread = {
  id: string;
  name: string;
  createdAtMs: number;
  updatedAtMs: number;
  messages: Array<AssistantHistoryMessage>;
};
