// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entity kinds the assistant can plan operations for.
 *
 * Phase 1 supports `routine`, `scene`, and `group`; the remaining kinds are
 * part of the approved surface and are added kind by kind.
 */
export type AssistantEntityKind = "routine" | "scene" | "group" | "device" | "floorplan" | "integration" | "helper" | "computed_source";
