// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantMessageRole } from "./AssistantMessageRole";
import type { AssistantThreadOutcome } from "./AssistantThreadOutcome";
import type { AssistantThreadProposal } from "./AssistantThreadProposal";

/**
 * One earlier conversation turn sent back with a new request. History is
 * client-held and session-only; the server caps and truncates it.
 */
export type AssistantHistoryMessage = { role: AssistantMessageRole, content: string, 
/**
 * The plan or action this turn proposed, stored so a reopened thread can
 * show what the assistant suggested. It is a record only — a proposal is
 * applied from the live session that produced it, not from history.
 */
proposal?: AssistantThreadProposal, 
/**
 * Result of applying that proposal, when the user applied it.
 */
outcome?: AssistantThreadOutcome, };
