// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantThreadOutcome } from "./AssistantThreadOutcome";

/**
 * Request body for recording the outcome of applying a stored proposal.
 */
export type AssistantThreadOutcomeRequest = { 
/**
 * `planId` or `actionId` of the proposal inside the stored thread.
 */
proposalId: string, outcome: AssistantThreadOutcome, };
