// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One persisted assistant conversation as listed in the panel. Message
 * contents are only included when a single thread is fetched.
 */
export type AssistantThreadSummary = {
  id: string;
  name: string;
  updatedAtMs: number;
  messageCount: number;
};
