// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantEntityKind } from './AssistantEntityKind';
import type { AssistantOpKind } from './AssistantOpKind';
import type { JsonValue } from './serde_json/JsonValue';

/**
 * One proposed configuration operation inside a plan.
 */
export type AssistantOperation = {
  /**
   * Stable per-plan id (`op-1`, `op-2`, ...) used for accept/apply.
   */
  opId: string;
  op: AssistantOpKind;
  kind: AssistantEntityKind;
  /**
   * Existing entity id for update/delete.
   */
  targetId?: string;
  /**
   * Human label shown in the review list.
   */
  label: string;
  /**
   * Masked snapshot before the operation (update/delete).
   */
  before?: JsonValue;
  /**
   * Proposed final state (create/update).
   */
  after?: JsonValue;
  /**
   * Destructive or in-use warnings surfaced during review.
   */
  warnings?: Array<string>;
};
