// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of one applied (or rejected) action change.
 */
export type AssistantActionChangeResult = {
  deviceKey: string;
  name?: string;
  ok: boolean;
  error?: string;
};
