// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantAttachment } from './AssistantAttachment';
import type { AssistantHistoryMessage } from './AssistantHistoryMessage';

export type AssistantPlanRequest = {
  prompt: string;
  attachments: Array<AssistantAttachment>;
  /**
   * Prior plan turns, oldest first. Capped and truncated server-side.
   */
  history?: Array<AssistantHistoryMessage>;
};
