// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantActionChange } from "./AssistantActionChange";

/**
 * A stored, reviewable light-state action produced by the unified assistant.
 * Like plans, actions are in-memory only, single-use, and expire.
 */
export type AssistantAction = { actionId: string, summary: string, changes: Array<AssistantActionChange>, createdAtMs: bigint, expiresAtMs: bigint, model: string, };
