// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantActionChangeResult } from "./AssistantActionChangeResult";
import type { AssistantOperationResult } from "./AssistantOperationResult";

/**
 * What became of a stored proposal: the result of applying it, recorded so a
 * reopened conversation shows the same applied state the user last saw.
 */
export type AssistantThreadOutcome = { "kind": "plan", results: Array<AssistantOperationResult>, acceptedOperationIds: Array<string>, } | { "kind": "action", results: Array<AssistantActionChangeResult>, };
