// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color component of a proposed light-state change.
 */
export type AssistantActionColor = { h: number; s: number };
