// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantAttachment } from './AssistantAttachment';
import type { AssistantHistoryMessage } from './AssistantHistoryMessage';

/**
 * Unified assistant request: one prompt that the server routes to either a
 * reviewed configuration plan or a proposed light-state action.
 */
export type AssistantChatRequest = {
  prompt: string;
  attachments: Array<AssistantAttachment>;
  /**
   * Optional device scope for light-state actions (for example the current
   * floorplan selection). Empty means every controllable device.
   */
  deviceKeys?: Array<string>;
  history?: Array<AssistantHistoryMessage>;
  /**
   * Persisted thread to continue. When set, the stored messages are used as
   * history and the new turn is appended to the thread.
   */
  threadId?: string;
};
