// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantMessageRole } from "./AssistantMessageRole";
import type { AssistantThreadProposal } from "./AssistantThreadProposal";

/**
 * One earlier conversation turn sent back with a new request. History is
 * client-held and session-only; the server caps and truncates it.
 */
export type AssistantHistoryMessage = { role: AssistantMessageRole, content: string, 
/**
 * The plan or action this turn proposed, stored so a reopened thread can
 * show what the assistant suggested. The proposal itself has expired by
 * then and is only a record — it cannot be applied from history.
 */
proposal?: AssistantThreadProposal, };
