// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entity kinds the assistant can plan operations for.
 */
export type AssistantEntityKind =
  | 'routine'
  | 'scene'
  | 'group'
  | 'device'
  | 'floorplan'
  | 'integration'
  | 'helper'
  | 'computed_source';
