// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockInput } from './BlockInput';
import type { BlockKind } from './BlockKind';
import type { JsonValue } from './serde_json/JsonValue';

export type AutomationBlock = {
  id: string;
  name: string;
  description: string;
  revision: bigint;
  inputs: { [key in string]: BlockInput };
  /**
   * ConditionExpr, NativeAction templates, or a JavaScript body with ScriptSpec
   * and a typed output for functions. A whole JSON value
   * may be replaced with {"$input":"name"}; source strings are never interpolated.
   */
  body: JsonValue;
  kind: BlockKind;
};
