// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar policy for cron schedules (K). The DST defaults are fixed for now:
 * nonexistent spring-forward locals are skipped and repeated fall-back locals
 * run once at the earlier occurrence. Backlog handling is explicit and
 * distinct from scheduler lateness.
 */
export type BacklogPolicy = 'skip' | 'catch_up_once';
