// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockInputKind } from './BlockInputKind';
import type { JsonValue } from './serde_json/JsonValue';

export type BlockInput = {
  label: string;
  kind: BlockInputKind;
  default?: JsonValue;
};
