// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlockInputKind =
  | { kind: 'group' }
  | { kind: 'scene' }
  | { kind: 'helper' }
  | { kind: 'device' }
  | { kind: 'targets' }
  | { kind: 'rollout' }
  | { kind: 'boolean' }
  | { kind: 'number' }
  | { kind: 'duration' }
  | { kind: 'string' }
  | { kind: 'enum'; options: Array<string> };
