// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One editable brightness anchor: `logical` is the brightness a person sees in
 * homectl, `output` is the brightness command sent to the device. Both are
 * fractions in `(0, 1]`; an empty curve means identity.
 */
export type BrightnessCalibrationPoint = { logical: number; output: number };
