// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionExpr } from './ConditionExpr';
import type { NativeAction } from './NativeAction';
import type { NodeId } from './NodeId';

export type ChooseBranch = {
  id: NodeId;
  condition: ConditionExpr;
  steps: Array<NativeAction>;
};
