// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceColor } from './DeviceColor';

/**
 * Parameters of the versioned circadian-compatibility preset. Field units
 * are explicit: fade starts are `HH:MM` civil times, fade durations are
 * whole hours (matching the legacy integration), and color temperature is
 * Kelvin.
 *
 * Unlike the legacy integration, the v2 preset validates strictly: zero or
 * negative durations, cross-midnight windows, overlapping fades, and
 * out-of-range brightness are reported instead of silently interpreted.
 */
export type CircadianCompatParams = {
  /**
   * `HH:MM` local time when the night-to-day fade starts.
   */
  day_fade_start: string;
  /**
   * Whole hours the day fade takes. Must not cross midnight.
   */
  day_fade_duration_hours: bigint;
  day_color: DeviceColor;
  day_brightness?: number;
  /**
   * `HH:MM` local time when the day-to-night fade starts.
   */
  night_fade_start: string;
  /**
   * Whole hours the night fade takes. Must not cross midnight.
   */
  night_fade_duration_hours: bigint;
  night_color: DeviceColor;
  night_brightness?: number;
};
