// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorCalibrationPoint } from "./ColorCalibrationPoint";

export type ColorCalibrationProfile = { id: string, name: string, points: Array<ColorCalibrationPoint>, reference_device_key: string | null, brightness: number, };
