// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hs } from "./Hs";

export type ColorCalibrationPoint = { reference: Hs, output: Hs, };
