// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrightnessCalibrationPoint } from './BrightnessCalibrationPoint';
import type { ColorCalibrationPoint } from './ColorCalibrationPoint';

export type ColorCalibrationProfile = {
  id: string;
  name: string;
  points: Array<ColorCalibrationPoint>;
  reference_device_key: string | null;
  /**
   * Light level used while matching color points. Metadata only — never an
   * anchor or curve parameter — and defaulted so a brightness-only profile
   * needs no color setup.
   */
  brightness: number;
  /**
   * Brightness anchors; empty means identity.
   */
  brightness_points: Array<BrightnessCalibrationPoint>;
};
