// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionTraceNode } from './ConditionTraceNode';
import type { TruthValue } from './TruthValue';
import type { UnknownReason } from './UnknownReason';

/**
 * Result of one condition evaluation. When `error` is set the `truth` field
 * must not be interpreted as a decision; `not`/`all`/`any` all stay errors.
 */
export type ConditionEvaluation = {
  truth: TruthValue;
  error?: string;
  unknown_reason?: UnknownReason;
  trace: ConditionTraceNode;
};
