// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from './GroupId';
import type { Quantifier } from './Quantifier';
import type { RawRuleOperator } from './RawRuleOperator';
import type { SceneId } from './SceneId';
import type { ValueSource } from './ValueSource';
import type { JsonValue } from './serde_json/JsonValue';

/**
 * Three-valued condition expression. `All`/`Any` require at least one child.
 */
export type ConditionExpr =
  | { kind: 'literal'; value: boolean }
  | { kind: 'all'; conditions: Array<ConditionExpr> }
  | { kind: 'any'; conditions: Array<ConditionExpr> }
  | { kind: 'not'; condition: ConditionExpr }
  | {
      kind: 'comparison';
      source: ValueSource;
      operator: RawRuleOperator;
      value?: JsonValue;
    }
  | {
      kind: 'group';
      group_id: GroupId;
      quantifier: Quantifier;
      power?: boolean;
      scene?: SceneId;
    };
