// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupEvaluation } from './GroupEvaluation';
import type { NodeId } from './NodeId';
import type { TruthValue } from './TruthValue';
import type { UnknownReason } from './UnknownReason';

/**
 * One node in a complete condition trace. The evaluator visits every node of
 * an eligible condition tree; short-circuiting requires an explicit semantics
 * review and is not implemented.
 */
export type ConditionTraceNode = {
  /**
   * JSON-pointer-style path of this node in the stored definition.
   */
  path: string;
  node_id?: NodeId;
  truth: TruthValue;
  evaluated: boolean;
  error?: string;
  unknown_reason?: UnknownReason;
  /**
   * Full group evaluation for group condition nodes, so native results,
   * SDK helpers, and UI traces agree exactly (G07).
   */
  group?: GroupEvaluation;
  children?: Array<ConditionTraceNode>;
};
