// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersistenceStatus } from "./PersistenceStatus";

/**
 * Runtime application and durability are separate outcomes.
 */
export type ConfigWriteStatus = { applied: boolean, persistence: PersistenceStatus, warning: string | null, };
