// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticEntity } from "./DiagnosticEntity";
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

export type ConfigDiagnostic = { id: string, severity: DiagnosticSeverity, entity: DiagnosticEntity, entity_id: string, name: string, code: string, message: string, suggestion: string, };
