// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticEntity } from './DiagnosticEntity';
import type { DiagnosticSeverity } from './DiagnosticSeverity';

export type ConfigDiagnostic = {
  id: string;
  severity: DiagnosticSeverity;
  entity: DiagnosticEntity;
  entity_id: string;
  name: string;
  code: string;
  message: string;
  suggestion: string;
  /**
   * Explicit device references; consumers never parse keys from messages.
   */
  device_keys: Array<string>;
  /**
   * The reference the issue is about inside the entity (a device key,
   * group ID or scene ID); empty when it concerns the entity as a whole.
   * Lets the UI offer a targeted repair without parsing the message.
   */
  reference: string;
};
