// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigDiagnostic } from "./ConfigDiagnostic";

/**
 * Read-only inspection of one immutable runtime snapshot. Scripts are not executed.
 */
export type ConfigDiagnostics = { warming_up: boolean, issues: Array<ConfigDiagnostic>, };
