// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ControllableState } from "./ControllableState";
import type { DeviceStateSource } from "./DeviceStateSource";
import type { ManageKind } from "./ManageKind";
import type { SceneId } from "./SceneId";

/**
 * lights with adjustable brightness and/or color
 */
export type ControllableDevice = { scene_id: SceneId | null, state_source: DeviceStateSource | null, capabilities: Capabilities, state: ControllableState, managed: ManageKind, };
