// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ControllableState } from "./ControllableState";
import type { DeviceAvailability } from "./DeviceAvailability";
import type { DeviceReport } from "./DeviceReport";
import type { DeviceStateSource } from "./DeviceStateSource";
import type { ManageKind } from "./ManageKind";
import type { SceneId } from "./SceneId";

/**
 * Requested state and the latest separately observed integration report.
 */
export type ControllableDevice = {
/**
 * Projection of the integration's database-backed disabled_device_ids policy.
 */
disabled?: boolean, availability?: DeviceAvailability, last_report?: DeviceReport, requested_at_ms?: number, scene_id: SceneId | null, state_source: DeviceStateSource | null, capabilities: Capabilities, state: ControllableState, managed: ManageKind, };
