// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from './SceneId';
import type { TargetSpec } from './TargetSpec';

/**
 * One scene in a cycle list: the scene plus optional target and transition
 * overrides for its activation.
 */
export type CycleSceneSpec = {
  scene_id: SceneId;
  targets: TargetSpec;
  /**
   * Preserve scene-derived transitions during activation. Defaults to true
   * like `ActivateScene`; the converter stores the v1 value explicitly.
   */
  use_scene_transition: boolean;
  transition_ms?: bigint;
};
