// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrightnessCalibrationPoint } from './BrightnessCalibrationPoint';
import type { ColorCalibrationPoint } from './ColorCalibrationPoint';

export type DeviceColorCalibration = {
  device_key: string;
  points: Array<ColorCalibrationPoint>;
  /**
   * Brightness anchors resolved for this device; empty means identity.
   */
  brightness_points: Array<BrightnessCalibrationPoint>;
};
