// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceHealthIssue } from './DeviceHealthIssue';
import type { EffectiveReportingPolicy } from './EffectiveReportingPolicy';

export type DeviceHealth = {
  device_key: string;
  integration_id: string;
  name: string;
  status: string;
  effective_policy: EffectiveReportingPolicy;
  last_fresh_report_ms: number | null;
  last_cached_report_ms: number | null;
  expected_by_ms: number | null;
  issues: Array<DeviceHealthIssue>;
};
