// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceIdRef } from "./DeviceIdRef";

/**
 * A reference to a device by canonical id.
 */
export type DeviceRef = DeviceIdRef;
