// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceHealth } from './DeviceHealth';

export type DeviceHealthSnapshot = {
  evaluated_at_ms: number;
  warming_up: boolean;
  devices: { [key in string]: DeviceHealth };
  /**
   * Sorted and deduplicated across every health issue on a device.
   */
  attention_device_keys: Array<string>;
};
