// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllableState } from "./ControllableState";

/**
 * Latest integration report, separate from the requested device state.
 */
export type DeviceReport = { state: ControllableState, received_at_ms: number, retained: boolean, matches_requested: boolean, };
