// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { DevicesState } from "./DevicesState";

export type DevicesPatch = { upserted: DevicesState, removed: Array<DeviceKey>, };
