// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { TriggerMode } from "./TriggerMode";

export type DeviceRule = { power: boolean | null, scene: SceneId | null, 
/**
 * How this rule should trigger. Defaults to `level` for device rules.
 */
trigger_mode: TriggerMode, };
