// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceColor } from "./DeviceColor";
import type { DeviceKey } from "./DeviceKey";

/**
 * A patch expressing user intent. Omitted fields preserve actor-owned state.
 */
export type DeviceCommand = { request_id: string, device_key: DeviceKey, power: boolean | null, brightness: number | null, color: DeviceColor | null, transition: number | null, preserve_scene: boolean, };
