// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acknowledges application to runtime state, not physical device delivery.
 */
export type DeviceCommandResult = { request_id: string, applied: boolean, error: string | null, };
