// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { DeviceStateSourceKind } from "./DeviceStateSourceKind";
import type { DeviceStateSourceScope } from "./DeviceStateSourceScope";
import type { GroupId } from "./GroupId";
import type { SceneId } from "./SceneId";

export type DeviceStateSource = { scope: DeviceStateSourceScope, kind: DeviceStateSourceKind, group_id: GroupId | null, linked_scene_id: SceneId | null, linked_device_key: DeviceKey | null, };
