// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportingPolicy } from './ReportingPolicy';

export type EffectiveReportingPolicy = {
  source: string;
  policy: ReportingPolicy;
  description: string;
  scheduling_grace_seconds: number;
};
