// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identity of an event within one process (boot) lifetime.
 */
export type EventId = { boot_id: bigint; sequence: bigint };
