// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from './Action';
import type { Device } from './Device';
import type { DeviceKey } from './DeviceKey';
import type { EventCausation } from './EventCausation';
import type { EventId } from './EventId';
import type { EventOrigin } from './EventOrigin';
import type { HelperId } from './HelperId';
import type { RoutineId } from './RoutineId';
import type { SceneConfig } from './SceneConfig';
import type { SceneId } from './SceneId';
import type { SourceId } from './SourceId';
import type { TimerIntentCapture } from './TimerIntentCapture';
import type { TimerOperation } from './TimerOperation';
import type { TimerWakeupJob } from './TimerWakeupJob';
import type { JsonValue } from './serde_json/JsonValue';

export type Event =
  | {
      DeviceAvailability: {
        device_key: DeviceKey;
        online: boolean;
        observed_at_ms: number;
        /**
         * Integration instance that observed the availability change.
         */
        integration_epoch: bigint | null;
      };
    }
  | {
      ExternalStateUpdate: {
        device: Device;
        /**
         * Integration instance that produced the report.
         */
        integration_epoch: bigint | null;
      };
    }
  | {
      InternalStateUpdate: {
        device_key: DeviceKey;
        old: Device | null;
        new: Device;
        /**
         * Process-unique identity for this event. Optional for backward
         * compatibility with older persisted/serialized events.
         */
        event_id: EventId | null;
        /**
         * Classification of the mutation origin.
         */
        origin: EventOrigin | null;
        /**
         * Causation metadata when this update was derived from a routine.
         */
        causation: EventCausation | null;
      };
    }
  | { SetExternalState: { device: Device } }
  | {
      SetInternalState: {
        device: Device;
        /**
         * Whether to skip sending [Event::SetExternalState] as a result of this state update.
         */
        skip_external_update: boolean | null;
        /**
         * Whether to skip persisting the device state to DB as a result of this state update.
         */
        skip_db_update: boolean | null;
        /**
         * Mutation origin. Defaults to [`EventOrigin::Derived`] when omitted.
         */
        origin: EventOrigin | null;
        /**
         * Causation metadata when this command was derived from a routine.
         */
        causation: EventCausation | null;
        /**
         * Integration instance that produced this state publication.
         */
        integration_epoch: bigint | null;
      };
    }
  | {
      ApplyDeviceState: {
        device: Device;
        /**
         * Whether to skip sending [Event::SetExternalState] as a result of this state update.
         */
        skip_external_update: boolean | null;
        /**
         * Whether to skip persisting the device state to DB as a result of this state update.
         */
        skip_db_update: boolean | null;
        /**
         * Mutation origin. Defaults to [`EventOrigin::Derived`] when omitted.
         */
        origin: EventOrigin | null;
        /**
         * Causation metadata when this state change was derived from a routine.
         */
        causation: EventCausation | null;
      };
    }
  | { RoutineAction: { action: Action; causation: EventCausation } }
  | {
      RoutineSetHelper: {
        helper: HelperId;
        value: JsonValue;
        causation: EventCausation;
      };
    }
  | {
      RoutineScriptResult: {
        routine_id: RoutineId;
        request_id: bigint;
        owner_key: string;
        owner_generation: bigint;
        definition_revision: bigint;
        state_revision: bigint;
        causation: EventCausation;
        /**
         * Strictly serialized worker result when the invocation succeeded.
         */
        value?: JsonValue | null;
        /**
         * Bounded failure message when the worker reported an error.
         */
        error?: string | null;
      };
    }
  | {
      RuleScriptLeafResult: {
        routine_id: RoutineId;
        request_id: bigint;
        owner_key: string;
        owner_generation: bigint;
        definition_revision: bigint;
        state_revision: bigint;
        /**
         * Strictly coerced v1 boolean result when the invocation succeeded.
         */
        value?: JsonValue | null;
        /**
         * Bounded failure message when the worker reported an error.
         */
        error?: string | null;
      };
    }
  | {
      SceneMaterializedResult: {
        scene_id: SceneId;
        request_id: bigint;
        owner_key: string;
        owner_generation: bigint;
        definition_revision: bigint;
        state_revision: bigint;
        /**
         * Raw legacy JSON result when the invocation succeeded.
         */
        value?: JsonValue | null;
        /**
         * Bounded failure message when the worker reported an error.
         */
        error?: string | null;
      };
    }
  | {
      SourceScriptResult: {
        source_id: SourceId;
        request_id: bigint;
        owner_key: string;
        owner_generation: bigint;
        definition_revision: bigint;
        state_revision: bigint;
        /**
         * Strictly serialized worker result when the invocation succeeded.
         */
        value?: JsonValue | null;
        /**
         * Bounded failure message when the worker reported an error.
         */
        error?: string | null;
      };
    }
  | {
      RoutineTimerOperation: {
        routine_id: RoutineId;
        definition_revision: bigint;
        operation: TimerOperation;
        /**
         * Frozen intent targets the scheduling step asked to capture (J08).
         */
        capture?: TimerIntentCapture | null;
        causation: EventCausation;
      };
    }
  | {
      TimerWakeup: {
        routine_id: RoutineId;
        definition_revision: bigint;
        job: TimerWakeupJob;
        generation: bigint;
        due_wall_ms: number;
      };
    }
  | 'SourceRefreshTick'
  | 'StartupCompleted'
  | { DbStoreScene: { scene_id: SceneId; config: SceneConfig } }
  | { DbEditScene: { scene_id: SceneId; name: string } }
  | { DbDeleteScene: { scene_id: SceneId } }
  | { Action: Action };
