// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from './EventId';

/**
 * Causation metadata carried by derived commands and recorded on frames.
 *
 * `depth` counts action dispatch hops since the root event. `parent_event_id`
 * points at the frame that directly emitted the command. `cause_id` points at
 * the root frame of the chain and is preserved across hops for tracing.
 */
export type EventCausation = {
  depth: number;
  parent_event_id: EventId | null;
  cause_id: EventId | null;
};
