// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an event came from. Automation v2 uses this to keep raw physical
 * evidence separate from desired-state commands and internal derivations.
 */
export type EventOrigin = 'report' | 'command' | 'derived' | 'startup';
