// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionMode } from './ExecutionMode';

export type ExecutionPolicy = {
  mode: ExecutionMode;
  /**
   * Upper bound on dispatched actions per invocation.
   */
  max_actions: number;
  /**
   * Optional minimum spacing between invocations.
   */
  min_interval_ms?: bigint;
};
