// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from './DeviceKey';
import type { GroupId } from './GroupId';

/**
 * Members of one captured group as resolved at plan time.
 */
export type FrozenGroupMembers = { group: GroupId; devices: Array<DeviceKey> };
