// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from './DeviceKey';
import type { SceneId } from './SceneId';
import type { UnknownReason } from './UnknownReason';

/**
 * Per-member result of a group evaluation, including unresolved configured
 * members (G01/G02).
 */
export type GroupMemberEvaluation = {
  /**
   * Configured reference as written in the group definition.
   */
  device: string;
  device_key?: DeviceKey;
  present: boolean;
  power?: boolean;
  scene_id?: SceneId;
  unknown_reason?: UnknownReason;
};
