// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from './GroupId';
import type { GroupMemberEvaluation } from './GroupMemberEvaluation';
import type { GroupSceneSummary } from './GroupSceneSummary';
import type { Quantifier } from './Quantifier';
import type { TruthValue } from './TruthValue';
import type { UnknownReason } from './UnknownReason';

/**
 * Shared group evaluation used by native rules, SDK helpers (P07), and
 * explanations (G07).
 */
export type GroupEvaluation = {
  group_id: GroupId;
  quantifier: Quantifier;
  /**
   * All configured members, deduplicated across nested groups, including
   * unresolved references.
   */
  configured_count: number;
  true_count: number;
  false_count: number;
  unknown_count: number;
  members: Array<GroupMemberEvaluation>;
  truth: TruthValue;
  reasons?: Array<UnknownReason>;
  scene: GroupSceneSummary;
};
