// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupSceneSummaryKind } from './GroupSceneSummaryKind';
import type { SceneId } from './SceneId';

/**
 * Common assigned-scene summary. Never inferred from a majority or the first
 * device (G05).
 */
export type GroupSceneSummary = {
  kind: GroupSceneSummaryKind;
  scene_id?: SceneId;
  assigned_count: number;
  unassigned_count: number;
  unknown_count: number;
};
