// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the assigned scene of a group's configured members summarizes.
 */
export type GroupSceneSummaryKind =
  'uniform' | 'unassigned' | 'mixed' | 'unknown';
