// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { SceneId } from "./SceneId";
import type { TriggerMode } from "./TriggerMode";

export type GroupRule = { group_id: GroupId, power: boolean | null, scene: SceneId | null, 
/**
 * How this rule should trigger. Defaults to `level` for group rules.
 */
trigger_mode: TriggerMode, };
