// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a helper value. Helpers become settable in P05;
 * P03 only resolves references against the catalog.
 */
export type HelperId = string;
