// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Declared type and constraints of a helper.
 */
export type HelperKind =
  | { kind: 'boolean' }
  | { kind: 'enum'; options: Array<string> }
  | { kind: 'number'; min?: number; max?: number }
  | { kind: 'string' };
