// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a helper's current value survives restarts.
 */
export type HelperPersistence = 'durable' | 'session';
