// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HelperId } from './HelperId';
import type { HelperKind } from './HelperKind';
import type { HelperPersistence } from './HelperPersistence';
import type { JsonValue } from './serde_json/JsonValue';

/**
 * A helper definition plus its initial value.
 */
export type HelperDefinition = {
  id: HelperId;
  name: string;
  kind: HelperKind;
  /**
   * Value used before any durable/current value exists.
   */
  initial_value: JsonValue;
  persistence: HelperPersistence;
  hidden?: boolean;
};
