// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HelperId } from './HelperId';
import type { HelperKind } from './HelperKind';
import type { HelperPersistence } from './HelperPersistence';
import type { JsonValue } from './serde_json/JsonValue';

/**
 * API/runtime view of one helper.
 */
export type HelperRuntimeStatus = {
  id: HelperId;
  name: string;
  kind: HelperKind;
  value: JsonValue;
  initial_value: JsonValue;
  revision: bigint;
  persistence: HelperPersistence;
  hidden?: boolean;
};
