// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HelperComputeStatus = {
  state: string;
  evaluated_at_ms: bigint | null;
  error: string | null;
};
