// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HelperId } from './HelperId';
import type { ScriptSpec } from './ScriptSpec';

/**
 * A read-only value calculated in the supervised JavaScript worker.
 */
export type HelperComputation = {
  script: ScriptSpec;
  helpers: Array<HelperId>;
  refresh_ms: bigint;
  enabled: boolean;
  revision: bigint;
};
