// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationConfigFieldSchema } from './IntegrationConfigFieldSchema';

export type IntegrationConfigSchema = {
  plugin: string;
  name: string;
  description: string;
  fields: Array<IntegrationConfigFieldSchema>;
};
