// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceColor } from './DeviceColor';

/**
 * Bounded, validated output of a light-profile source.
 */
export type LightProfile = {
  /**
   * Explicit color, if the source produces one.
   */
  color?: DeviceColor;
  /**
   * Optional brightness in `0.0..=1.0`.
   */
  brightness?: number;
  /**
   * Optional device transition in milliseconds.
   */
  transition_ms?: bigint;
};
