// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChooseBranch } from './ChooseBranch';
import type { CycleSceneSpec } from './CycleSceneSpec';
import type { DeviceRef } from './DeviceRef';
import type { HelperId } from './HelperId';
import type { InvokeMode } from './InvokeMode';
import type { NodeId } from './NodeId';
import type { RolloutSpec } from './RolloutSpec';
import type { RoutineId } from './RoutineId';
import type { SceneId } from './SceneId';
import type { SceneSelection } from './SceneSelection';
import type { TargetSpec } from './TargetSpec';
import type { TimerId } from './TimerId';
import type { JsonValue } from './serde_json/JsonValue';

/**
 * One typed native action with a stable node ID.
 */
export type NativeAction =
  | {
      action: 'activate_scene';
      id: NodeId;
      scene_id?: SceneId;
      select?: SceneSelection;
      targets: TargetSpec;
      /**
       * Preserve scene-derived transitions during activation. Defaults to
       * true for native definitions (v1 action descriptors default to
       * false; the converter stores the v1 value explicitly).
       */
      use_scene_transition: boolean;
      /**
       * Explicit transition override in milliseconds.
       */
      transition_ms?: bigint;
      /**
       * Stagger the activation across target positions.
       */
      rollout?: RolloutSpec;
    }
  | {
      action: 'cycle_scenes';
      id: NodeId;
      scenes: Array<CycleSceneSpec>;
      nowrap: boolean;
      /**
       * Restrict current-scene detection to these devices/groups. Empty
       * uses every device common to the cycled scenes.
       */
      detection: TargetSpec;
      rollout?: RolloutSpec;
    }
  | { action: 'set_power'; id: NodeId; device: DeviceRef; power: boolean }
  | {
      action: 'dim';
      id: NodeId;
      targets: TargetSpec;
      step: number;
      transition_ms?: bigint;
    }
  | {
      action: 'randomize_color';
      id: NodeId;
      targets: TargetSpec;
      /**
       * Inclusive saturation bounds in 0.0..=1.0. Missing values default to
       * 0.2..=1.0; out-of-range values are clamped at execution, and the
       * bounds are swapped when reversed.
       */
      min_saturation?: number;
      max_saturation?: number;
      /**
       * Explicit transition override in milliseconds.
       */
      transition_ms?: bigint;
    }
  | { action: 'choose'; id: NodeId; branches: Array<ChooseBranch> }
  | {
      action: 'schedule_timer';
      id: NodeId;
      timer: TimerId;
      delay_ms: bigint;
      /**
       * Freeze intent tokens for these targets at actor acceptance (J08).
       */
      capture_target_intents?: TargetSpec;
    }
  | {
      action: 'replace_timer';
      id: NodeId;
      timer: TimerId;
      delay_ms: bigint;
      /**
       * Freeze intent tokens for these targets at actor acceptance (J08).
       */
      capture_target_intents?: TargetSpec;
    }
  | { action: 'cancel_timer'; id: NodeId; timer: TimerId }
  | { action: 'set_helper'; id: NodeId; helper: HelperId; value: JsonValue }
  | {
      action: 'invoke_routine';
      id: NodeId;
      routine_id: RoutineId;
      mode: InvokeMode;
    };
