// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedStepStatus } from './PlannedStepStatus';

/**
 * Observable outcome of accepting and dispatching one routine run (X03).
 * Matching ([`TriggerRuntimeStatus`]) is separate from acceptance (this type)
 * and from per-step dispatch ([`PlannedStepStatus`]).
 */
export type PlannedRunStatus = {
  /**
   * Monotonic run id within this process.
   */
  run_id: bigint;
  definition_revision: bigint;
  /**
   * Whether the plan was accepted (triggers matched and condition passed).
   */
  accepted: boolean;
  steps: Array<PlannedStepStatus>;
  /**
   * Steps dropped by the bounded execution queue (A08).
   */
  dropped: bigint;
};
