// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from './NodeId';
import type { StepDisposition } from './StepDisposition';

/**
 * Observable outcome of one planned native step (X02).
 */
export type PlannedStepStatus = {
  action_id: NodeId;
  /**
   * Native action kind, e.g. `activate_scene`.
   */
  kind: string;
  /**
   * Fully resolved targets as stable strings (device keys, group/scene IDs,
   * or helper IDs). Frozen at plan time.
   */
  targets: Array<string>;
  disposition: StepDisposition;
  reason?: string;
};
