// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from './NodeId';

export type PreviewStep = { id: NodeId; kind: string; targets: Array<string> };
