// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeProgram } from './NativeProgram';
import type { ScriptProgram } from './ScriptProgram';

/**
 * Tagged program body: native typed actions or a sandboxed script.
 */
export type Program =
  ({ kind: 'native' } & NativeProgram) | ({ kind: 'script' } & ScriptProgram);
