// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
import type { DeviceKey } from './DeviceKey';

export type RandomizeColorActionDescriptor = {
  device_keys: Array<DeviceKey>;
  min_saturation: number | null;
  max_saturation: number | null;
  transition: number | null;
};
