// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from './DeviceKey';

export type RandomizeColorActionDescriptor = {
  /**
   * Devices whose colors should be randomized.
   */
  device_keys: Array<DeviceKey>;
  /**
   * Inclusive lower and upper saturation bounds. Defaults to 0.2..=1.0.
   */
  min_saturation: number | null;
  max_saturation: number | null;
  /**
   * Optional transition time in seconds.
   */
  transition: number | null;
};
