// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawRuleOperator } from "./RawRuleOperator";
import type { TriggerMode } from "./TriggerMode";
import type { JsonValue } from "./serde_json/JsonValue";

export type RawRule = { path: string, operator: RawRuleOperator, value: JsonValue | null, 
/**
 * How this rule should trigger. Defaults to `pulse`, matching sensor rules.
 */
trigger_mode: TriggerMode, };
