// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RawRuleOperator = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "contains" | "starts_with" | "exists" | "truthy" | "regex";
