// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stored in widget_settings under reporting/{scope}/{id}. Missing rows inherit.
 */
export type ReportingPolicy =
  | { mode: 'inherit' }
  | { mode: 'ignore' }
  | { mode: 'custom'; expected_interval_seconds: number };
