// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRef } from './DeviceRef';

export type RolloutSource =
  { kind: 'device'; device: DeviceRef } | { kind: 'triggering_device' };
