// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolloutSource } from './RolloutSource';
import type { RolloutStyle } from './RolloutStyle';

/**
 * Staggered activation of scene targets. The style mirrors the v1 rollout
 * options; the source is either a fixed device or the routine's triggering
 * device, resolved at plan time from the matched trigger.
 */
export type RolloutSpec = {
  style: RolloutStyle;
  source?: RolloutSource;
  /**
   * Total spread in milliseconds; targets without a saved position apply
   * immediately, and a missing/zero duration applies everything at once.
   */
  duration_ms?: bigint;
};
