// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { RoutineHistoryTriggerKind } from "./RoutineHistoryTriggerKind";
import type { RoutineId } from "./RoutineId";
import type { RoutineRuntimeStatus } from "./RoutineRuntimeStatus";
import type { RoutineV2RuntimeStatus } from "./RoutineV2RuntimeStatus";

export type RoutineHistoryEntry = { id: string, timestamp: string, routine_id: RoutineId, routine_name: string, trigger_kind: RoutineHistoryTriggerKind, event_source_device_key: DeviceKey | null, action_count: number, status: RoutineRuntimeStatus | null, 
/**
 * Evaluation and run snapshot for v2 entries: matched trigger ids, the
 * condition trace, and the planned step dispositions. Absent for v1
 * entries, which carry `status` instead.
 */
v2?: RoutineV2RuntimeStatus, 
/**
 * How many identical blocked attempts this entry stands for. Absent on
 * older entries and on runs; read it as one.
 */
occurrence_count?: number, 
/**
 * When the first of the coalesced attempts happened. Only set once an
 * entry stands for more than one attempt.
 */
first_timestamp?: string, 
/**
 * Short reason a matched trigger produced no run.
 */
blocked_reason?: string, };
