// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionEvaluation } from './ConditionEvaluation';
import type { NodeId } from './NodeId';
import type { PlannedRunStatus } from './PlannedRunStatus';
import type { TriggerRuntimeStatus } from './TriggerRuntimeStatus';

/**
 * Observable v2 evaluation state for one routine.
 */
export type RoutineV2RuntimeStatus = {
  definition_revision: bigint;
  fingerprint: string;
  /**
   * Trigger IDs that fired for the current/last evaluated frame, in
   * stable declaration order. One event matching several triggers lists
   * all of them and invokes the routine once (T01).
   */
  matched_trigger_ids: Array<NodeId>;
  triggers: Array<TriggerRuntimeStatus>;
  condition: ConditionEvaluation;
  /**
   * Known-true condition plus at least one fired trigger.
   */
  will_trigger: boolean;
  /**
   * P04 evaluates decisions; action planning and dispatch land in P05.
   */
  execution_pending: boolean;
  /**
   * Outcome of the most recent accepted plan for this routine (P05/X03).
   */
  last_run?: PlannedRunStatus;
};
