// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionExpr } from './ConditionExpr';
import type { ExecutionPolicy } from './ExecutionPolicy';
import type { Program } from './Program';
import type { TriggerSpec } from './TriggerSpec';

/**
 * Versioned v2 routine definition.
 */
export type RoutineDefinitionV2 = {
  triggers: Array<TriggerSpec>;
  /**
   * Omitted conditions normalize to literal `true`.
   */
  condition: ConditionExpr;
  program: Program;
  execution: ExecutionPolicy;
};
