// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionEvaluation } from "./ConditionEvaluation";
import type { PlannedStepStatus } from "./PlannedStepStatus";
import type { PreviewStep } from "./PreviewStep";
import type { PreviewValidationError } from "./PreviewValidationError";

export type RoutinePreviewResponse = { error: string | null, validation_errors: Array<PreviewValidationError>, condition: ConditionEvaluation | null, would_run: boolean, steps: Array<PreviewStep>, suppressions: Array<PlannedStepStatus>, script_unsupported: boolean, };
