// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutineV2RuntimeStatus } from './RoutineV2RuntimeStatus';
import type { RuleRuntimeStatus } from './RuleRuntimeStatus';

export type RoutineRuntimeStatus = {
  all_conditions_match: boolean;
  will_trigger: boolean;
  rules: Array<RuleRuntimeStatus>;
  /**
   * P04 v2 evaluation detail. Absent for v1 rows and quarantined rows.
   */
  v2?: RoutineV2RuntimeStatus;
};
