// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoutineHistoryTriggerKind = "rule_match" | "force_trigger" | "v2_run" | "v2_blocked";
