// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleRuntimeStatus } from "./RuleRuntimeStatus";

export type RoutineRuntimeStatus = { all_conditions_match: boolean, will_trigger: boolean, rules: Array<RuleRuntimeStatus>, };
