// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutinePreviewOverride } from './RoutinePreviewOverride';
import type { JsonValue } from './serde_json/JsonValue';

export type RoutinePreviewRequest = {
  definition: JsonValue;
  trigger_id: string;
  overrides: Array<RoutinePreviewOverride>;
};
