// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyRule } from "./AnyRule";
import type { DeviceRule } from "./DeviceRule";
import type { GroupRule } from "./GroupRule";
import type { ScriptRule } from "./ScriptRule";
import type { SensorRule } from "./SensorRule";

export type Rule = SensorRule | DeviceRule | GroupRule | AnyRule | ScriptRule;
