// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuleRuntimeStatus = { condition_match: boolean, trigger_match: boolean, error: string | null, children: Array<RuleRuntimeStatus> | null, };
