// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { GroupId } from "./GroupId";
import type { SceneId } from "./SceneId";

/**
 * Activate a scene immediately. Omitted scopes mean all writable scene targets;
 * explicit empty scopes never mean all devices. No rollout or replay is implied.
 */
export type SceneCommand = { request_id: string, scene_id: SceneId, device_keys: Array<DeviceKey> | null, group_keys: Array<GroupId> | null, use_scene_transition: boolean, transition: number | null, };
