// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from './GroupId';
import type { HelperId } from './HelperId';
import type { SceneId } from './SceneId';

/**
 * Decision-time scene selection for a v2 activation. Resolved once at plan
 * time and frozen into the plan (A01).
 */
export type SceneSelection =
  | {
      kind: 'helper_enum';
      helper: HelperId;
      mapping: { [key in string]: SceneId };
      fallback_scene_id?: SceneId;
    }
  | { kind: 'group_active'; group_id: GroupId; fallback_scene_id?: SceneId };
