// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";

/**
 * Confirms runtime application, not integration delivery or physical state.
 */
export type SceneCommandResult = { request_id: string, applied: boolean, affected_devices: Array<DeviceKey>, error: string | null, };
