// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacklogPolicy } from './BacklogPolicy';

export type ScheduleSpec = {
  /**
   * Six-field cron (`second minute hour day-of-month month day-of-week`).
   * The DOM/DOW-OR behavior is preserved; calendar resolution is our own
   * (croner only parses the grammar).
   */
  cron?: string;
  every_ms?: bigint;
  /**
   * IANA timezone name (or a fixed offset). Calendar schedules should store
   * an explicit IANA zone so DST behavior is stable.
   */
  timezone?: string;
  /**
   * Missed-occurrence handling for cron schedules.
   */
  backlog: BacklogPolicy;
  /**
   * Bounded lateness for the single coalesced catch-up. Required when
   * `backlog` is `catch_up_once` and rejected otherwise.
   */
  catch_up_lateness_ms?: bigint;
};
