// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptDeclaration } from './ScriptDeclaration';

/**
 * Versioned script body plus declared subscriptions. The body is a function
 * body (unambiguous `return`) executed only by the P06 worker.
 */
export type ScriptSpec = {
  api_version: number;
  /**
   * Function body source. Never executed during compilation or validation.
   */
  source_body: string;
  declarations: Array<ScriptDeclaration>;
  limits_profile: string;
};
