// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A JavaScript-based rule that evaluates a script returning boolean
 */
export type ScriptRule = { 
/**
 * JavaScript code that should return a boolean value.
 * Has access to `devices` and `groups` global objects.
 */
script: string, };
