// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRef } from "./DeviceRef";
import type { GroupId } from "./GroupId";
import type { TimerId } from "./TimerId";

/**
 * A declared read/subscription of a script program. A scripted trigger is a
 * declaration plus a pure filter; scripts cannot register hidden listeners.
 */
export type ScriptDeclaration = { "kind": "device", device: DeviceRef, } | { "kind": "group", group_id: GroupId, } | { "kind": "timer", timer: TimerId, };
