// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptSpec } from './ScriptSpec';

export type ScriptProgram = { spec: ScriptSpec };
