// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A persisted sensor change; id is also the pagination cursor.
 */
export type SensorHistoryEntry = { id: number, source_key: string, changed_at_ms: number, value: JsonValue, };
