// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensorDevice } from "./SensorDevice";
import type { TriggerMode } from "./TriggerMode";

export type SensorRule = { state: SensorDevice, 
/**
 * How this rule should trigger. Defaults to `pulse` for sensors.
 */
trigger_mode: TriggerMode, };
