// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LightProfile } from './LightProfile';
import type { SourceQuality } from './SourceQuality';

/**
 * Last computed output plus provenance. `definition_revision` and
 * `computed_at_ms` let consumers detect stale or superseded results.
 */
export type SourceOutput = {
  profile: LightProfile;
  quality: SourceQuality;
  definition_revision: bigint;
  /**
   * Wall-clock time of the successful computation this output came from.
   */
  computed_at_ms: bigint;
  /**
   * Injected civil time used for the computation (`HH:MM:SS`), when the
   * source computes against local time.
   */
  local_time?: string;
};
