// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness of the last computed output. A failed evaluation retains the
 * last good value as `stale`, never as healthy.
 */
export type SourceQuality =
  { quality: 'fresh' } | { quality: 'stale'; message: string };
