// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identity of a shipped source preset, pinned in the definition so a later
 * preset update is a deliberate migration instead of a silent change.
 */
export type SourcePresetRef = { id: string; version: number };
