// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircadianCompatParams } from "./CircadianCompatParams";

/**
 * How a computed source derives its output.
 */
export type SourceCompute = { "kind": "circadian_compat", preset_version: number, params: CircadianCompatParams, };
