// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LightProfile } from './LightProfile';

/**
 * One previewed profile value at a wall-clock instant.
 */
export type SourcePreviewSample = {
  /**
   * Wall-clock instant the profile was computed at.
   */
  time_ms: bigint;
  /**
   * Civil time label in the source timezone (`HH:MM`).
   */
  local_time: string;
  profile: LightProfile;
};
