// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircadianCompatParams } from './CircadianCompatParams';
import type { SourcePresetRef } from './SourcePresetRef';
import type { JsonValue } from './serde_json/JsonValue';

/**
 * How a computed source derives its output.
 */
export type SourceCompute =
  | {
      kind: 'circadian_compat';
      preset_version: number;
      params: CircadianCompatParams;
    }
  | {
      kind: 'script';
      preset?: SourcePresetRef;
      source_body?: string;
      params: JsonValue;
    };
