// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from './serde_json/JsonValue';

/**
 * Metadata of a shipped preset version, including the forkable body. The
 * parameter object stays `params`-shaped JSON so the authoring form can show
 * it without a second schema language.
 */
export type SourcePresetInfo = {
  id: string;
  version: number;
  name: string;
  description: string;
  default_params: JsonValue;
  source_body: string;
};
