// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from './DeviceKey';
import type { SourceCompute } from './SourceCompute';
import type { SourceId } from './SourceId';

/**
 * DB-backed computed source definition. The canonical device key is
 * `computed/<id>`; `aliases` lists legacy keys (for example
 * `circadian/color`) that resolve to the same single entity so group
 * membership is not double-counted.
 */
export type SourceDefinition = {
  id: SourceId;
  name: string;
  enabled: boolean;
  /**
   * Definition revision; bumped on every write so consumers can reject
   * superseded results.
   */
  revision: bigint;
  /**
   * IANA zone used to derive civil time for the computation.
   */
  timezone: string;
  /**
   * Refresh cadence in milliseconds. Startup always computes once.
   */
  refresh_interval_ms: bigint;
  /**
   * Legacy device keys this source also answers for.
   */
  aliases?: Array<DeviceKey>;
  compute: SourceCompute;
};
