// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceCompute } from './SourceCompute';

/**
 * Request body for the stateless computed-source preview. The definition is
 * not persisted; the editor posts its draft as-is.
 */
export type SourcePreviewRequest = {
  /**
   * IANA zone or fixed offset used to derive civil time.
   */
  timezone: string;
  compute: SourceCompute;
  samples?: number;
};
