// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a computed source. Computed sources arrive in P11;
 * P03 only resolves references against the catalog.
 */
export type SourceId = string;
