// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourcePreviewSample } from './SourcePreviewSample';

/**
 * One local day of a computed source's output, sampled at a fixed step.
 */
export type SourcePreview = {
  timezone: string;
  /**
   * Sampled local day start (the instant of local midnight).
   */
  day_start_ms: bigint;
  /**
   * Step between samples in milliseconds.
   */
  step_ms: bigint;
  samples: Array<SourcePreviewSample>;
  /**
   * Set when the compute kind cannot be previewed synchronously; the
   * sample list is then empty.
   */
  unsupported_reason?: string;
  /**
   * Set when the preview is a faithful stand-in rather than the exact
   * runtime path (for example the shipped script preset).
   */
  note?: string;
};
