// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevicesPatch } from "./DevicesPatch";
import type { FlattenedGroupsConfig } from "./FlattenedGroupsConfig";
import type { FlattenedScenesConfig } from "./FlattenedScenesConfig";
import type { RoutineStatuses } from "./RoutineStatuses";
import type { JsonValue } from "./serde_json/JsonValue";

export type StatePatch = { devices: DevicesPatch | null, scenes: FlattenedScenesConfig | null, groups: FlattenedGroupsConfig | null, routine_statuses: RoutineStatuses | null, ui_state: { [key in string]?: JsonValue } | null, };
