// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevicesPatch } from "./DevicesPatch";
import type { FlattenedGroupsConfig } from "./FlattenedGroupsConfig";
import type { FlattenedScenesConfig } from "./FlattenedScenesConfig";
import type { HelperRuntimeStatus } from "./HelperRuntimeStatus";
import type { RoutineStatusesPatch } from "./RoutineStatusesPatch";
import type { TimerRuntimeStatus } from "./TimerRuntimeStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type StatePatch = { 
/**
 * Revision of this patch; apply only when it follows the last seen one.
 */
revision: number, devices: DevicesPatch | null, scenes: FlattenedScenesConfig | null, groups: FlattenedGroupsConfig | null, routine_statuses: RoutineStatusesPatch | null, timers: Array<TimerRuntimeStatus> | null, helper_statuses: Array<HelperRuntimeStatus> | null, ui_state: { [key in string]: JsonValue } | null, };
