// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevicesState } from './DevicesState';
import type { FlattenedGroupsConfig } from './FlattenedGroupsConfig';
import type { FlattenedScenesConfig } from './FlattenedScenesConfig';
import type { HelperRuntimeStatus } from './HelperRuntimeStatus';
import type { RoutineStatuses } from './RoutineStatuses';
import type { TimerRuntimeStatus } from './TimerRuntimeStatus';
import type { JsonValue } from './serde_json/JsonValue';

export type StateUpdate = {
  /**
   * Monotonic revision of this full state.
   */
  revision: number;
  devices: DevicesState;
  scenes: FlattenedScenesConfig;
  groups: FlattenedGroupsConfig;
  routine_statuses: RoutineStatuses;
  /**
   * Live named timer jobs (P09). `remaining_ms` is a publish-time sample;
   * clients should count down from `due_wall_ms`.
   */
  timers: Array<TimerRuntimeStatus>;
  /**
   * Current helper values (P12). Widgets and editors read these instead of
   * polling the config API.
   */
  helper_statuses: Array<HelperRuntimeStatus>;
  ui_state: { [key in string]: JsonValue };
};
