// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRef } from './DeviceRef';
import type { GroupId } from './GroupId';

export type TargetSpec = {
  devices?: Array<DeviceRef>;
  groups?: Array<GroupId>;
};
