// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerIntentTarget } from "./TimerIntentTarget";

/**
 * Intent targets captured when a timer is scheduled (J08). The actor records
 * the tokens at acceptance, after earlier plan steps have bumped intents, and
 * a delayed plan may act only on unchanged tokens.
 */
export type TimerIntentCapture = { targets: Array<TimerIntentTarget>, };
