// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a named timer within its owning routine. Not
 * globally unique: two routines may each own an `"off"` timer.
 */
export type TimerId = string;
