// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";

/**
 * One capturable intent target. Group capture needs frozen membership (J09)
 * and is rejected at compile time until that lands.
 */
export type TimerIntentTarget = { "kind": "device", device: DeviceKey, };
