// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from './DeviceKey';
import type { GroupId } from './GroupId';

/**
 * One capturable intent target.
 */
export type TimerIntentTarget =
  { kind: 'device'; device: DeviceKey } | { kind: 'group'; group: GroupId };
