// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutineId } from './RoutineId';
import type { TimerId } from './TimerId';
import type { TimerJobStatus } from './TimerJobStatus';
import type { TimerPersistence } from './TimerPersistence';

/**
 * One live timer job as published to readers.
 */
export type TimerRuntimeStatus = {
  routine_id: RoutineId;
  definition_revision: bigint;
  timer: TimerId;
  generation: bigint;
  status: TimerJobStatus;
  /**
   * UTC deadline estimate in milliseconds since the Unix epoch.
   */
  due_wall_ms: number;
  /**
   * Sampled remaining monotonic duration at publish time.
   */
  remaining_ms: number;
  persistence: TimerPersistence;
};
