// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerId } from './TimerId';

/**
 * One timer mutation produced by a plan step (P09). Timer state is
 * actor-authoritative; the plan only names the operation.
 */
export type TimerOperation =
  | { operation: 'schedule'; timer: TimerId; delay_ms: bigint }
  | { operation: 'replace'; timer: TimerId; delay_ms: bigint }
  | { operation: 'cancel'; timer: TimerId };
