// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrozenGroupMembers } from './FrozenGroupMembers';
import type { TimerIntentTarget } from './TimerIntentTarget';

/**
 * Intent targets captured when a timer is scheduled (J08/J09). The actor
 * records the tokens at acceptance, after earlier plan steps have bumped
 * intents, and a delayed plan may act only on unchanged tokens and on the
 * group membership frozen here.
 */
export type TimerIntentCapture = {
  targets: Array<TimerIntentTarget>;
  /**
   * Group membership resolved at plan time (J09). A delayed action may not
   * expand a captured group to members added after the capture.
   */
  frozen_members?: Array<FrozenGroupMembers>;
};
