// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from './NodeId';
import type { TimerId } from './TimerId';

/**
 * Which authoritative job store entry a wakeup belongs to (P09).
 */
export type TimerWakeupJob =
  | { job: 'named_timer'; timer: TimerId }
  | { job: 'predicate_deadline'; trigger: NodeId }
  | { job: 'schedule_occurrence'; trigger: NodeId };
