// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionExpr } from './ConditionExpr';
import type { DeviceRef } from './DeviceRef';
import type { NodeId } from './NodeId';
import type { ScheduleSpec } from './ScheduleSpec';
import type { StateChangeMode } from './StateChangeMode';
import type { TimerId } from './TimerId';

/**
 * A declared trigger subscription with a stable ID and tagged body.
 */
export type TriggerSpec =
  | { kind: 'report'; id: NodeId; device: DeviceRef; field?: string }
  | {
      kind: 'state_change';
      id: NodeId;
      device: DeviceRef;
      mode: StateChangeMode;
    }
  | { kind: 'predicate_transition'; id: NodeId; predicate: ConditionExpr }
  | {
      kind: 'predicate_for';
      id: NodeId;
      predicate: ConditionExpr;
      duration_ms: bigint;
    }
  | { kind: 'schedule'; id: NodeId; schedule: ScheduleSpec }
  | { kind: 'timer_fired'; id: NodeId; timer: TimerId }
  | { kind: 'startup'; id: NodeId }
  | { kind: 'manual'; id: NodeId };
