// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Determines how a rule triggers in response to state changes.
 */
export type TriggerMode = "pulse" | "edge" | "level";
