// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Strong three-valued logic result. Errors are represented separately on the
 * enclosing evaluation, never as a truth value.
 */
export type TruthValue = 'true' | 'false' | 'unknown';
