// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

export type UiLogEntry = { timestamp: string, level: LogLevel, target: string, message: string, };
