// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogEntityReference } from './LogEntityReference';
import type { LogLevel } from './LogLevel';
import type { JsonValue } from './serde_json/JsonValue';

export type UiLogEntry = {
  timestamp: string;
  level: LogLevel;
  target: string;
  message: string;
  references?: Array<LogEntityReference>;
  details?: JsonValue;
};
