// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTimerDefinition } from './UserTimerDefinition';
import type { UserTimerRuntime } from './UserTimerRuntime';

export type UserTimerEntry = {
  definition: UserTimerDefinition;
  runtime: UserTimerRuntime;
};
