// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTimerAction } from './UserTimerAction';
import type { UserTimerSchedule } from './UserTimerSchedule';

export type UserTimerDefinition = {
  id: string;
  name: string;
  icon: string;
  enabled: boolean;
  schedule: UserTimerSchedule;
  action: UserTimerAction;
  finish_action: UserTimerAction | null;
};
