// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTimerEntry } from './UserTimerEntry';

export type UserTimers = {
  timers: Array<UserTimerEntry>;
  legacy_migrated: boolean;
};
