// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserTimerAction =
  | { kind: 'device'; device_key: string; power: boolean }
  | { kind: 'group'; group_id: string; power: boolean }
  | { kind: 'scene'; scene_id: string };
