// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserTimerRuntime = {
  next_start_ms: number | null;
  finish_ms: number | null;
  active: boolean;
  /**
   * Durable intent, retried after an interrupted command. Commands are
   * idempotent state assignments; integration delivery is not acknowledged.
   */
  pending: string | null;
  last_message: string | null;
  last_run_ms: number | null;
};
