// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserTimerSchedule =
  | { kind: 'countdown'; minutes: number }
  | {
      kind: 'scheduled';
      time: string;
      timezone: string;
      /**
       * A date for a one-off timer; otherwise weekdays must be nonempty.
       */
      date: string | null;
      /**
       * ISO weekday numbers: Monday = 1, Sunday = 7.
       */
      weekdays: Array<number>;
      duration_minutes: number | null;
    }
  | {
      kind: 'ready_by';
      time: string;
      timezone: string;
      date: string | null;
      weekdays: Array<number>;
      warmup_minutes: number;
    };
