// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnknownReason } from "./UnknownReason";
import type { JsonValue } from "./serde_json/JsonValue";

export type ValueFieldInfo = { path: string, type: string, value: JsonValue | null, available: boolean, reason: UnknownReason | null, error: string | null, };
