// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRef } from './DeviceRef';
import type { HelperId } from './HelperId';
import type { SourceId } from './SourceId';

export type ValueSource =
  | { kind: 'device'; device: DeviceRef; path: string }
  | { kind: 'helper'; helper: HelperId }
  | { kind: 'computed_source'; source: SourceId; path: string };
