// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceCommand } from "./DeviceCommand";
import type { Event } from "./Event";
import type { SceneCommand } from "./SceneCommand";

export type WebSocketRequest = { "DeviceCommand": DeviceCommand } | { "SceneCommand": SceneCommand } | { "EventMessage": Event };
