// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceCommandResult } from "./DeviceCommandResult";
import type { StatePatch } from "./StatePatch";
import type { StateUpdate } from "./StateUpdate";

export type WebSocketResponse = { "DeviceCommandResult": DeviceCommandResult } | { "State": StateUpdate } | { "Patch": StatePatch };
