version: "3"
services:
  postgres:
    container_name: "homectl-postgres"
    image: "postgres"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
            - "0.0.0.0:5432:5432"
    # command: ["postgres", "-c", "log_statement=all"]
  migrations:
    container_name: "homectl-migrations"
    build:
      context: .
      dockerfile: ./Dockerfile.migrations
    environment:
      DATABASE_URL: "postgres://postgres@homectl-postgres/homectl"
    depends_on:
      - postgres
  homectl:
    container_name: "homectl"
    build: .
    # ports:
    # - "56700:56700/udp"
    # Required for lifx UDP broadcast traffic?
    network_mode: host
    environment:
      # DATABASE_URL: "postgres://postgres@homectl-postgres/homectl"
      DATABASE_URL: "postgres://postgres@localhost/homectl"
    depends_on:
      - migrations