version: "3"
services:
  postgres:
    container_name: "postgres-homectl"
    image: "postgres"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
            - "0.0.0.0:5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
