name: UI CI

on:
  push:
    branches: ["main"]
    paths:
      - 'ui/**'
      - 'Dockerfile'
      - '.github/workflows/ui-ci.yml'
  pull_request:
    paths:
      - 'ui/**'
      - 'Dockerfile'
      - '.github/workflows/ui-ci.yml'
  workflow_dispatch: {}

jobs:
  conventional-commit:
    name: Conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2

  build-ui:
    name: Typecheck & build UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Set up pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 12.6.0

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.23.3
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm tsc --pretty false

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
